server:
  port: 8080
  address: 127.0.0.1

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbc?useUnicode=true&characterEncoding=utf-8
    username: root
    password:


mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    root:  info
    org.springframework:  info
    org.mybatis:  DEBUG
